### ISSUE TITLE
General observations

### ISSUE THREAD

**Issue by WorldThirteen** [Olexis73/Weather#1]
## General
- ![image](https://user-images.githubusercontent.com/14346393/49557292-dcdb8600-f90f-11e8-9496-ee5b3ffbd938.png)
An image is not fully cover the page. Also, may you need to center your content on a free page space
- A map is not working
- Service worker and manifest are not working
## Code
- I think some parts could be not a separate component, but just be a part of parent jsx, files like:
https://github.com/Olexis73/Weather/blob/master/src/precipitation.jsx
https://github.com/Olexis73/Weather/blob/master/src/pressure.jsx
https://github.com/Olexis73/Weather/blob/master/src/temperature.jsx
https://github.com/Olexis73/Weather/blob/master/src/wind.jsx
https://github.com/Olexis73/Weather/blob/master/src/clouds.jsx
https://github.com/Olexis73/Weather/blob/master/src/description.jsx
https://github.com/Olexis73/Weather/blob/master/src/humidity.jsx
Other code looks good, it's simple, clean and readable.

**Comment by Olexis73** [comment]
Thanks for the comment. I will try to fix it.
